# Generated by Django 5.0 on 2024-01-05 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_trainer2', '0007_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_trainer2.city'),
        ),
    ]
