# Generated by Django 5.0 on 2024-01-06 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_trainer2', '0008_alter_client_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_trainer2.book')),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_trainer2.buy')),
            ],
        ),
    ]
