# Generated by Django 5.0 on 2024-01-06 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_trainer2', '0010_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_step_beg', models.DateField(blank=True)),
                ('date_step_end', models.DateField(blank=True)),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_trainer2.buy')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_trainer2.step')),
            ],
        ),
    ]
