# Generated by Django 5.0 on 2023-12-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_trainer', '0004_supply_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='buy',
        ),
        migrations.AddField(
            model_name='book',
            name='buy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
