# Generated by Django 5.0 on 2023-12-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_trainer', '0005_remove_supply_buy_book_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='buy',
            field=models.IntegerField(null=True),
        ),
    ]
