# Generated by Django 5.0 on 2023-12-27 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_trainer', '0006_alter_book_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='buy',
        ),
    ]
