# Generated by Django 5.0 on 2023-12-19 13:46

import django.db.models.deletion
import myapp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MyModelA',
            fields=[
                ('char_a', models.CharField(max_length=255)),
                ('text_a', models.TextField(blank=True, verbose_name='text_a verbose name')),
                ('integer_a', models.IntegerField(null=True)),
                ('choice_a', models.CharField(choices=[('CH1', 'Choice1'), ('CH2', 'Choice2'), ('CH3', 'Choice3')], max_length=255)),
                ('db_column_a', models.CharField(db_column='db_column_aaaaaa', help_text='this is help text', max_length=255)),
                ('db_index_a', models.CharField(db_index=True, default='This is db_index field', max_length=255)),
                ('editable_false_a', models.CharField(max_length=255)),
                ('date_field_a', models.DateField(null=True, unique_for_date=True)),
                ('even_a', models.IntegerField(validators=[myapp.models.MyModelA.validate_even])),
                ('duration_a', models.DurationField()),
                ('email_a', models.EmailField(max_length=254)),
                ('file_field_a', models.FileField(upload_to='./for_file_field')),
                ('filefield_patch_a', models.FilePathField(path='/home/sa/Documents')),
                ('image_field_a', models.ImageField(upload_to='')),
                ('IP_field_a', models.GenericIPAddressField()),
                ('JSON_field_a', models.JSONField()),
                ('slug_a', models.SlugField()),
                ('time_field_a', models.TimeField()),
                ('URL_field_a', models.URLField()),
                ('uuid_id_a', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MyModelB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.IntegerField()),
                ('my_foreigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mymodelb')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.author')),
                ('book_genre', models.ManyToManyField(to='myapp.genre')),
                ('book_producer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.producer')),
            ],
        ),
    ]
